#!/usr/bin/env bash
# Generates a cloudflared config pointing at the local OAuth HTTP service
# (dist/oauth-http-cli.js, default port 3738) so it's reachable at a public
# HTTPS hostname for the claude.ai custom connector.
#
# This script does the parts that CAN be automated locally. It cannot do
# the interactive `cloudflared tunnel login` browser flow or actually
# create anything in your Cloudflare account for you — those steps are
# printed at the end for you to run yourself. See docs/deploy.md and
# HANDOFF.md for the full checklist.
#
# Usage:
#   TUNNEL_NAME=obsidian-everywhere \
#   TUNNEL_HOSTNAME=obsidian.example.com \
#   LOCAL_PORT=3738 \
#   ./scripts/setup-cloudflare-tunnel.sh

set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-obsidian-everywhere}"
LOCAL_PORT="${LOCAL_PORT:-3738}"
: "${TUNNEL_HOSTNAME:?Set TUNNEL_HOSTNAME to the public hostname you want, e.g. obsidian.example.com}"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared is not installed."
  echo "  macOS: brew install cloudflared"
  echo "  other: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  exit 1
fi

CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/${TUNNEL_NAME}.yml"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/setup-cloudflare-tunnel.sh
tunnel: ${TUNNEL_NAME}
credentials-file: ${CONFIG_DIR}/${TUNNEL_NAME}.json

ingress:
  - hostname: ${TUNNEL_HOSTNAME}
    service: http://localhost:${LOCAL_PORT}
  - service: http_status:404
EOF

echo "Wrote $CONFIG_FILE"
echo
echo "Remaining steps (require your Cloudflare account — run these yourself):"
echo "  1. cloudflared tunnel login"
echo "  2. cloudflared tunnel create ${TUNNEL_NAME}"
echo "     (this writes ${CONFIG_DIR}/${TUNNEL_NAME}.json — the credentials-file above expects it there)"
echo "  3. cloudflared tunnel route dns ${TUNNEL_NAME} ${TUNNEL_HOSTNAME}"
echo "  4. cloudflared tunnel --config ${CONFIG_FILE} run ${TUNNEL_NAME}"
echo "     (or: cloudflared service install --config ${CONFIG_FILE}  to run it as a system service)"
echo
echo "Once the tunnel is up, set OAUTH_ISSUER_URL=https://${TUNNEL_HOSTNAME} when starting"
echo "dist/oauth-http-cli.js (see docker-compose.yml / .env.example)."
